humanmade/S3-Uploads

- inc/class-s3-uploads-image-editor-imagick.php
- inc/class-s3-uploads.php
- tests/test-s3-uploads-image-editor-imagick.php
We have to provide a custom save method as imagick can't handle saving to
s3:// urls
> Add support for Imagick by subclass WP_Image_Editor_Imagick

- README.md
- inc/class-s3-uploads-stream-wrapper.php
We wanted to set defaults on Expires and cache controls, so we added a filter so you could modify the array passed to S3 via an external plugin / drop in.
However, since Expires & Cache-Control are probably quite popular, we added support for constants to be added to wp-config with the API keys to control this without requiring an additional drop-in to configure.
> Add filter for modifying S3 Object Paramaters

- README.md
- inc/class-s3-uploads-stream-wrapper.php
- inc/class-s3-uploads.php
- lib/aws-sdk/Aws/S3/StreamWrapper.php
- s3-uploads.php
- tests/test-s3-uploads-stream-wrapper.php
This moves the hacks we did have to the sdk into our own subclass, which makes
upgrading the SDK a lot simpler.
> Move the aws-sdk modifications to our own class

- inc/class-s3-uploads-wp-cli-command.php
- s3-uploads.php
- tests/bootstrap.php
Establishes a new constant and two CLI commands for enabling/disabling the plugin's URL rewriting mechanism.
If the constant `S3_UPLOADS_AUTOENABLE` is undefined or defined and set to true, the plugin behaves as usual. If it's defined and set to `false`, then the plugin will be active, but image URLs won't automatically point to S3 until explicitly enabled.
To enable the URL rewriting, you'd fire the `wp s3-uploads enable` command that's already documented in the readme. This command will set an autoloaded option in WordPress which is checked the same time as the constant above.
So, briefly:
If the constant is undefined
... or if the constant is defined and set to true
... or if the constant is defined and set to false and the WordPress option exists and is set to 'enabled'
then the …
> Enable the plugin via CLI

- inc/class-s3-uploads-stream-wrapper.php
- inc/class-s3-uploads.php
Based on existing work in the lazyload branch, this change defers the loading of the aws library functions until they are needed. Data from our production environments show this will save ~250ms per page load.
> Lazily load the s3 library

- s3-uploads.php
This avoids PHP fatal errors in unit tests, as those not always include
the necessary classes.
See #62.
> Add autoloader for plugin classes.

- inc/class-s3-uploads-wp-cli-command.php
- inc/class-s3-uploads.php
- s3-uploads.php
An autoloader for the plugin classes was introduced in d57dec0.
This change means that these class files do not have to be required
manually anymore.
> Remove require statements that are no longer needed.

- inc/class-s3-uploads-wp-cli-command.php
- inc/class-s3-uploads.php
- s3-uploads.php
The AWS SDK includes its own autoloader. As such, we should load this
file in the plugin’s bootstrap.
Only loading the autoloader file when needed leads to little gains, but
it results in bugs. This changes fixes #60.
> Always require AWS Autoloader

- s3-uploads.php
Add a notice when the requirements are not met, and return to avoid
executing the rest of the plugin.
Fixes #69.
> Check for PHP version requirements

- inc/class-s3-uploads-wp-cli-command.php
When using AWS Instance Profiles, no credentials (Key ID, Secret Key)
need to be set.
See #39.
> Adapt `verify` command for Instance Profiles.

- README.md
After adding the plugin files to your WordPress install you must activate the plugin before you can use the s3-uploads command line tools. 
I have added an extra step to the README.md file wit the WP-CLI activation command.
> Missing installation step added to README.md file.

- inc/class-s3-uploads-wp-cli-command.php
We are attempting to use this plugin for rolling out S3 Uploads across ~700 sites. Therefore, we need to be able to automate the installation process. This change will add a new WP CLI argument for the create-iam-user action which will result in a JSON encoded string being printed instead of the user friendly output that currently exists.
> Automation output improvement

- inc/class-s3-uploads-wp-cli-command.php
CLI verify steps bomb out now because `canola.jpg` doesn't exist, but `sunflower.jpg` does.
Fixes #117
> Update referenced file to prevent CLI error.

- s3-uploads.php
This pull request sets the minimum PHP version to 5.5.0, which is the minimum PHP version required by the AWS-SDK v3. It threw a fatal error when I tried to activate on a machine running 5.4.*
> Set minimum required PHP version to 5.5.0

- inc/class-s3-uploads-stream-wrapper.php
The PR prevents at PHP Warning triggered by `_wp_handle_upload()` calling `chmod()` on the custom S3 stream wrapper.
See https://github.com/humanmade/S3-Uploads/issues/134.
> Add missing `stream_metadata()` method

- inc/class-s3-uploads.php
The temporary file currently ends up in the `inc` directory as `s3-uploadsFILENAMErandom.tmp`. This doesn't work very well when the unix permissions are set to read-only for plugins. This moves things to `wp-content/s3-uploads`.
> Fixing temporary upload location

- composer.json
- s3-uploads.php
If the AWS SDK is already available, use it. Version compatibility is the responsibility of the user.
Additionally, when loaded via Composer, require the SDK via Composer. This allows Composer to handle version compatibility and such.
Fixes #142.
> Allow external AWS SDK

- README.md
- inc/class-s3-uploads.php
Allow the S3 object permissions to be controlled by use of a constant. Use case is when the WordPress contents should not be public. Existing public-read default is retained.
> add control of S3 object permissions

- inc/class-s3-uploads-wp-cli-command.php
This PR adds an `is_dir` check alongside the `file_exists` to improve file detection. This fixes warnings in the subsequent `copy` operation where the attachment's `_wp_attached_file` meta field is absent.
```log
Warning: copy(): The first argument to copy() function cannot be a directory in /srv/www/htdocs/wp-content/plugins/s3-uploads/inc/class-s3-uploads-wp-cli-command.php on line 121
```
> Ignores copy if file path is a directory

- inc/class-s3-uploads.php
The `wp_delete_file` filter  is used in two different ways by WordPress: 
1. When filtering the filename for the removal of thumbnails, extra image sizes, and backup sizes in `wp_delete_attachment()`, a relative path is expected in return. This relative path is then used to rebuild the absolute path before `unlink()` fires.
1. When filtering directly in `wp_delete_file()`, an absolute path is expected at all times.
We can identify when each of these is used by capturing the original file's absolute path when `delete_attachment` fires and only leaving that untouched. When `wp_delete_file()` is used directly, no original file is captured, so the path is left untouched.
This fixes a case where original files would not be deleted from S3 when removed from the media library, but where all of …
> Don't filter absolute paths in wp_delete_file()

- .gitattributes
It's possible to remove the `tests` (and some other files) from the git archive that composer downloads from github on install. This saves a few MB as we have test images / pdfs and videos in our tests directory
> Don't include tests in the downloadable composer package

- inc/class-s3-uploads.php
In WordPress 4.9.7, attachment file deleting changed again, which mangles the s3:// paths very badly. What's more, there's no hooks to be able to adjust / change this behaviour. More details in the code comment.
> Fix delete files on delete attachment

- inc/class-s3-uploads-image-editor-imagick.php
In some cases (it's not that clear how) Imagick is not compatible with remote streams. According to the docs, this has never been possible, but I think it happened to work in the past. I've tried the same version of imagick, on different sets and sometimes works, some times doesnt. The crux of the issue is that IMagick tries to read from the stream, and is sending a SEEK request to something near PHP_MAX_INT, which causes memory allocation issues on our stream wrapper. It's maybe possible to work around it with a seek stream guard, but really I think that's just one of many possible issues. I think it's going to be better to let IMagick always work with local images to avoid issues.
> Fix IMagick with s3 compat

- inc/class-s3-uploads-wp-cli-command.php
- verify.txt
`tests/` isn't included in the release package, so this instead uses a small text file to use for verification instead.
> Fix verify WP CLI command

- README.md
It seems like the `--sync` and `--dry-run` cli options were removed in fef7efb but were not removed from documentation which caused some confusion and I opened issue #327. This pull request simply removes them from README.md.
> Remove upload-directory --sync and --dry-run cli options from documentation as they were removed in fef7efb

- inc/class-s3-uploads.php
The use of unlink() breaks functionality of some third-party WordPress plugins.
The use of wp_delete_file() is preferred over unlink() since it allows filtering the file before deletion
Please consider including this in your codebase.
> Using wp_delete_file() instead of unlink()

- README.md
- inc/class-s3-uploads-wp-cli-command.php
- inc/class-s3-uploads.php
- s3-uploads.php
This is an experiment to support private / unpublished uploads. These files are pushed to S3 with a private ACL, and then URLs are generated and signed when pages are generated, with a time-based expiry.
> Add support for Private Attachments

- inc/class-s3-uploads.php
If `S3_UPLOADS_DISABLE_REPLACE_UPLOAD_URL` or `S3_UPLOADS_USE_LOCAL` is set, the prefetch resource hint shouldn't be registered to prevent an unused look up.
> Don't add resource hints if no external S3 URL is used

- inc/class-plugin.php
- inc/class-stream-wrapper.php
- tests/test-s3-uploads-stream-wrapper.php
- tests/test-s3-uploads.php
Please for give me for what I have done.
Fixes #373.
> Fix slow call to scandir() when uploading files

- inc/class-plugin.php
- inc/class-stream-wrapper.php
All requests right now will init the s3client, which causes a lot of file i/o in loading the aws sdk, and a fair bit of CPU to crunch through the sdk init.
Now we have this much better typed, I think we can do what we were never able to do in https://github.com/humanmade/S3-Uploads/pull/128
> Lazy load s3 client

- composer.json
- tests/test-s3-uploads.php
The latest version of Psalm-plugin-wordpress is Psalm 4, which needs some new upgrade steps. We'll do that, but first let's just switch back to the older version.
> Switch to fixed version of Psalm Plugin WordPress

- inc/class-plugin.php
Sets the "filesize" property in the attachment metadata when initially uploading images, so that it doesn't have to be queried for in the ajax response on `wp_prepare_attachment_for_js()`.
Fixes #492.
> Save filesize with attachment metadata on upload

- inc/class-s3-uploads.php
This PR manually backports the patch from #493 to the v2 branch.
See #492.
> Backport #493 to v2

- .github/workflows/build-release.yml
I added `workflow_dispatch` too, to be able to debug with https://github.blog/2021-04-15-work-with-github-actions-in-your-terminal-with-github-cli/
> Don't install dev deps in manual install

- inc/class-wp-cli-command.php
- was using incorrect namespace
- this fixes https://github.com/humanmade/S3-Uploads/issues/513
> Fix upload-directory command

- s3-uploads.php
This allows other plugins on the default priority to load correctly.
Fixes #540.
> Load S3 Uploads at 0 priority, rather than 10

- inc/class-wp-cli-command.php
> Fix spelling mistake in class-wp-cli-command.php

- inc/class-image-editor-imagick.php
If `WP_Image_Editor_Imagick::_save()` returns a `WP_Error` but no temp filename exists the `WP_Error` should still be returned. This prevents a fatal error `Cannot use object of type WP_Error as array` for the `$copy_result = copy( $save['path'], $filename );` line.
> Image Editor Imagick: Always return the WP_Error object of parent call

- README.md
Documentation in README.md suggests you can create an IAM user using the `create-iam-user ` subcommand, however this subcommand does not actually exist.
> Remove misleading documentation from README.md

- inc/class-stream-wrapper.php
- inc/class-wp-cli-command.php
A recent change in the AWS PHP SDK broke ListUploads with an explicit endpoint URL. Using the V2 version of the method solves the problem and the returned results are compatible with the previous version.
See: https://github.com/aws/aws-sdk-php/issues/2575
See: https://github.com/humanmade/altis-local-server/issues/542
> Use ListObjectsV2 where applicable

- composer.json
Composer currently fails to run an installation with the following:
```
Error: composer/installers contains a Composer plugin which is blocked by your allow-plugins config. You may add it to the list if you consider it safe.
```
This commit allows composer/installers to run by adding it to the safe list.
The failure is currently affecting this build action:
https://github.com/humanmade/S3-Uploads/actions/runs/3567321595
I'm not sure why this previous build action succeeds though:
https://github.com/humanmade/S3-Uploads/actions/runs/1922046645/jobs/2727425028
> Add composer/installers to allow-plugins

- inc/namespace.php
- s3-uploads.php
Makes manual installation work again, like suggested by felipeelia.
https://github.com/humanmade/S3-Uploads/issues/573#issuecomment-1151335081
> Move adding of wp-cli command to init()

- psalm/stubs/imagick.php
This PR fixes a linting error when running PHP's lint across the Imagick stub file.
When scanning our projects, including the S3 Uploads plugin, it was identified when running the lint command on new PHP versions.
System:
- PHP 7.4|8.0|8.1
Error:
```bash
Fatal error: Namespace declaration statement has to be the very first statement or after any declare call in the script in psalm/stubs/imagick.php on line 11
```
Recreate:
`php -l psalm/stubs/imagick.php`
Expect:
`No syntax errors detected in psalm/stubs/imagick.php`
Another option would be to exclude the `./psalm` directory from being included in the release via the `.gitattributes` file.
> Fixes: Fatal Error when running PHP lint command

- inc/namespace.php
I had a problem on one of the WordPress installation where directory returned by `sys_get_temp_dir` was not writeable by php and changing `WP_TEMP_DIR` did not help (because the plugin was not taking that into account).  
Changing `sys_get_temp_dir` to Wordpress function `get_temp_dir` helped.
> Use get_temp_dir instead of sys_get_temp_dir

- inc/class-stream-wrapper.php
- s3-uploads.php
As of PHP 8.0, substr will return empty string rather than false in certain circumstances.
From https://www.php.net/manual/en/function.substr.php : 
8.0.0 	The function returns an empty string where it previously returned false. 
Due to this change, this implementation of readdir in S3-Uploads behaves incorrectly. In particular, this common pattern:
while (($file = readdir($dh)) !== false){
which is used in gravityforms, becomes an infinite loop since the while loop just keeps getting an empty string rather than false.
This can lead to a crazy high AWS S3 list line item on your monthly bill. I recommend merging in this change right away to avoid this situation.
> fix readdir bug from PHP 8 substr change

- inc/class-local-stream-wrapper.php
- inc/class-plugin.php
When using the local stream wrapper on Windows machines, need to use "\\" directory separator instead of "/", otherwise `getLocalPath` always returns empty string
> Replace "/" with "\" on windows machines

- README.md
S3-compatible APIs may be broken with the latest AWS SDK, but can be worked around by disabling the checksums.
Fixes #681.
> Add note about checksums

- inc/class-local-stream-wrapper.php
- inc/class-stream-wrapper.php
Just two small, one character fixes for [PHP 8.4's deprecated notice around implicit nulls](https://wiki.php.net/rfc/deprecate-implicitly-nullable-types).
```
PHP Deprecated:  S3_Uploads\Stream_Wrapper::register(): Implicitly marking parameter $cache as nullable is deprecated, the explicit nullable type must be used instead in /plugins/s3-uploads/inc/class-stream-wrapper.php on line 119
```
This fix should be compatible all the way back to PHP 7.1
> Fix implicit nullable parameter deprecations in PHP 8.4

- README.md
Fixes: https://github.com/humanmade/S3-Uploads/issues/41
> Added a line to link best practices for managing AWS access keys
