humanmade/S3-Uploads

- README.md
- inc/class-s3-uploads-wp-cli-command.php
- inc/class-s3-uploads.php
- phpunit.xml.dist
- s3-uploads.php
- tests/bootstrap.php
- tests/test-s3-uplaods.php
> Enable the plugin via CLI

- README.md
This adds a header and credits section to the README. [Preview it](https://github.com/humanmade/S3-Uploads/blob/improve-readme/README.md).
Happy to change up if there's something you'd like to add/change/remove here.
> Improve the readme a tad

- inc/class-s3-uploads.php
> Add proxy information to AWS SDK config

- inc/class-s3-uploads-wp-cli-command.php
- The command now first verifies that the necessary constants are set.
- The copy and delete operations are now done on the S3 instance,
verifying that the setup is correct.
Fixes #39.
> Fix verify WP CLI command.

- inc/class-s3-uploads-image-editor-imagick.php
Unlink the temp filename once done, see #84
> Clean up temp files

- inc/class-s3-uploads-wp-cli-command.php
> Automation output improvement for create iam user

- README.md
A brief paragraph for describing the built-in URL rewrites capabilities for S3U.
> Update README to document `S3_UPLOADS_BUCKET_URL`

- README.md
> Document the format for S3_UPLOADS_BUCKET_URL

- inc/class-s3-uploads.php
Follow-up to #140 to change the temp directory to the default `get_temp_dir()`
> Change temporary directory to the default

- inc/class-s3-uploads-stream-wrapper.php
Address issue #177 to allow customisation of the call to putObject against S3 that tests the bucket is writable.
> add call to apply_filters for test push to S3

- README.md
Felt that this option deserved mention in Readme.md. I was looking for this option and didn't find it in the Readme, had to dig it up from a client site where it is in use. Wanted to add it here if for no other reason than so I can find it the next time I need it.
Feel free to change my wording to be more better.
> adding section about S3_UPLOADS_DISABLE_REPLACE_UPLOAD_URL to readme.md

- README.md
I was trying to setup for the Sydney region and it seems that value is also required so I added a link to the reference page that list the equivalent region for that parameter.
> Updated the details regarding the region

- inc/class-s3-uploads.php
> Add the DNS address for the S3 Bucket to list for DNS prefetch.

- README.md
Update docs for bucket path prefix and include an example to show how to use folders
> Update docs for bucket path prefix

- README.md
Ref: https://docs.aws.amazon.com/AmazonS3/latest/dev/AuthUsingTempSessionTokenPHP.html
> Add docs for configuring a session token

- README.md
> Improvement to the custom endpoint docs

- README.md
> Update travis badge to travis-ci.com

- README.md
> Document ability to use instance profiles

- README.md
- s3-uploads.php
- Adds version check that show notice if WP version is not 5.3
- Added requirements to readme in a more prominent way
The base of the PR needs to be changed, after #391 is merged.
> [3.0] Improve version requirements

- s3-uploads.php
A minor bit of polish adding an `s` to a protocol handler
> Use https instead of http in the plugin URI field

- .github/workflows/build-release.yml
Automates building manual-install.zip on release. Fixes #371.
Needs testing.
> Build manual-install on release

- inc/class-s3-uploads-stream-wrapper.php
> Backport slow scandir() operations

- inc/class-plugin.php
> Loosen type signature add_s3_signed_params_to_attachment_image_src

- tests/run-tests.sh
This only published from the master branch so there's not much we can do other than merge and hope!
> Publish type coverage to Psalm Shepherd

- inc/class-plugin.php
> fix: local stream wrapper class name

- inc/class-wp-cli-command.php
> Fix typo in class-wp-cli-command.php

- inc/class-plugin.php
I had use this functionality elsewhere and thought it should be part of the public API.
> Added `get_s3_path` function instead of hard coding s3 path.

- s3-uploads.php
The version number in the main plugin file is out of date with the release.
> Fix version number

- README.md
> docs: fix broken logo in README

- inc/class-plugin.php
> [Backport v3-branch] Scandir issue #634 and #630

- s3-uploads.php
Bumps the version to 3.0.10. 
See: #715
> Bump version to 3.0.10
